// Code generated by github.com/gnolang/gno. DO NOT EDIT.

//go:build gno
// +build gno

package grc20

import "errors"

var (
	ErrInsufficientBalance   = errors.New("insufficient balance")
	ErrInsufficientAllowance = errors.New("insufficient allowance")
	ErrInvalidAddress        = errors.New("invalid address")
	ErrCannotTransferToSelf  = errors.New("cannot send transfer to self")
)
