// Code generated by github.com/gnolang/gno. DO NOT EDIT.


// +build gno

package grc20

import "github.com/gnolang/gno/stdlibs/stdshim"

const zeroAddress = std.Address("")

func checkIsValidAddress(addr std.Address) error {
	if addr.String() == "" {
		return ErrInvalidAddress
	}
	return nil
}

func emit(event interface{}) {
	// TODO: setup a pubsub system here?
}
